name = "web-message-board"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "message-board-db"
database_id = "7ac4dd55-1c1c-4e10-910b-874e626e88d5"  #  D1 数据库 ID

# Rules for importing HTML file
[[rules]]
type = "Text"
globs = ["**/*.html"]
